//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTelefonica
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_contatos
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
    }
}
